test: update workflow results
Signed-off-by: chjmil <christopher.miller@sas.com>

diff --git a/.github/workflows/default_plan_unit_tests.yml b/.github/workflows/default_plan_unit_tests.yml
--- a/.github/workflows/default_plan_unit_tests.yml
+++ b/.github/workflows/default_plan_unit_tests.yml
@@ -9,17 +9,20 @@ jobs:
     runs-on: ubuntu-latest
     environment: terraformSecrets
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v4
       - name: Build Docker Image
         run: docker build -t viya4-iac-azure:terratest -f Dockerfile.terratest .
       - name: Run Tests
         working-directory: test
         run: |
+          mkdir -p $(pwd)/results
           docker run \
             -e TF_VAR_subscription_id=$TF_VAR_subscription_id \
             -e TF_VAR_tenant_id=$TF_VAR_tenant_id \
             -e TF_VAR_client_id=$TF_VAR_client_id \
             -e TF_VAR_client_secret=$TF_VAR_client_secret \
+            -v $(pwd)/results:/results \
             viya4-iac-azure:terratest
         env:
           # TF ENVIRONMENT
@@ -27,3 +30,13 @@ jobs:
           TF_VAR_tenant_id: "${{ secrets.TF_VAR_TENANT_ID }}"
           TF_VAR_client_id: "${{ secrets.TF_VAR_CLIENT_ID }}"
           TF_VAR_client_secret: "${{ secrets.TF_VAR_CLIENT_SECRET }}"
+      - name: Convert to JUnit XML
+        uses: jstemmer/go-junit-report@v0.9.1
+        with:
+          input: test/results/report.xml
+          output: test/junit/junit-report.xml
+      - name: Report JUnit Results
+        uses: mikepenz/action-junit-report@v2
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: test/junit/junit-report.xml
